### ISSUE TITLE
Show the magnitude of the features before the id  

### ISSUE THREAD

**Issue by antgonza** [biocore/qurro#232]
It will be neat to have the actual magnitude of each of the features in the display below:
<img width="673" alt="Screen Shot 2019-10-04 at 2 01 29 PM" src="https://user-images.githubusercontent.com/2014559/66236351-8239c480-e6af-11e9-9106-345ed70d05b7.png">

I can imagine something like:
```
(3.7) k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Corynebacteriales;f__Corynebacteriaceae;g__Corynebacterium;s__Corynebacterium_tuscaniense / g__Corynebacterium / s__Corynebacterium_tuscaniense

...
```

**Comment by fedarko** [comment]
Just to be clear, sorry—what does "magnitude" mean in this context? Do you mean the current differential/loading value for each feature? If so, this might be tricky since we'd need to update the selected feature displays on updating the rank plot.

A previous version of Qurro showed all of the differential values next to each feature in these text boxes. The problem with that was it was way too much information shown at once, esp. when there were >= ~5 columns of differentials.

Migrating these displays from text boxes to fancier tables (#197) will make it a lot easier to show arbitrary stuff here.
